package com.entercomm.bikeintercom.mesh

import com.entercomm.bikeintercom.mesh.protocol.PipeDelimitedMeshProtocol
import com.entercomm.bikeintercom.onboarding.GroupCodeUtils
import com.entercomm.bikeintercom.util.Logger
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test

/**
 * Integration tests for mesh network validation logic.
 * These tests verify that the validation patterns and discovery message handling
 * work correctly across different node ID formats and group codes.
 *
 * These tests would have caught:
 * - UUID_PATTERN not accepting node-XXXXXXXX format
 * - Group code format mismatch between generator and validator
 */
class MeshNetworkValidationTest {

    private lateinit var protocol: PipeDelimitedMeshProtocol

    @Before
    fun setUp() {
        Logger.isTestMode = true
        protocol = PipeDelimitedMeshProtocol()
    }

    @After
    fun tearDown() {
        Logger.isTestMode = false
    }

    // === Node ID Format Tests ===
    // These tests verify all valid nodeId formats are accepted

    @Test
    fun `node-XXXXXXXX format is valid for discovery`() {
        // This is the format generated by MeshNetworkManager.generateNodeId()
        val nodeIds = listOf(
            "node-aabbccdd",
            "node-11223344",
            "node-AABBCCDD",
            "node-ee0aad1b",
            "node-dadcb47c",
        )

        for (nodeId in nodeIds) {
            val payload = "$nodeId|TestDevice|OPEN"
            val message = createDiscoveryMessage(nodeId, payload)
            val serialized = protocol.serialize(message)
            val deserialized = protocol.deserialize(serialized, serialized.size)

            assertNotNull("Should deserialize node ID: $nodeId", deserialized)
            assertEquals(nodeId, deserialized!!.sourceId)

            // Verify payload round-trip
            val payloadString = String(deserialized.payload)
            assertTrue(
                "Payload should contain nodeId: $nodeId",
                payloadString.startsWith(nodeId),
            )
        }
    }

    @Test
    fun `UUID format is valid for discovery`() {
        // Standard UUID format should also be accepted
        val nodeIds = listOf(
            "550e8400-e29b-41d4-a716-446655440000",
            "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "AABBCCDD-1122-3344-5566-778899AABBCC",
        )

        for (nodeId in nodeIds) {
            val payload = "$nodeId|TestDevice|OPEN"
            val message = createDiscoveryMessage(nodeId, payload)
            val serialized = protocol.serialize(message)
            val deserialized = protocol.deserialize(serialized, serialized.size)

            assertNotNull("Should deserialize UUID: $nodeId", deserialized)
            assertEquals(nodeId, deserialized!!.sourceId)
        }
    }

    @Test
    fun `short hex format is valid for discovery`() {
        // Short hex strings (8-36 chars) should be valid
        val nodeIds = listOf(
            "abcd1234",
            "12345678",
            "aabbccdd",
            "a1b2c3d4e5f6",
        )

        for (nodeId in nodeIds) {
            val payload = "$nodeId|TestDevice|OPEN"
            val message = createDiscoveryMessage(nodeId, payload)
            val serialized = protocol.serialize(message)
            val deserialized = protocol.deserialize(serialized, serialized.size)

            assertNotNull("Should deserialize hex ID: $nodeId", deserialized)
        }
    }

    // === Group Code Format Tests ===
    // These tests verify group code generation and validation are compatible

    @Test
    fun `generated group code is valid for mesh filtering`() {
        // Generate multiple codes and verify they're all valid
        repeat(50) {
            val code = GroupCodeUtils.generateGroupCode()

            // Should be raw format (no dashes)
            assertFalse("Generated code should not contain dash", code.contains("-"))
            assertEquals("Generated code should be 6 chars", 6, code.length)

            // Should be valid according to validator
            assertTrue(
                "Generated code should be valid: $code",
                GroupCodeUtils.isValidGroupCode(code),
            )

            // Should only contain valid characters
            assertTrue(
                "All chars should be valid: $code",
                code.all { it in GroupCodeUtils.CODE_CHARS },
            )
        }
    }

    @Test
    fun `group code round-trip through discovery message`() {
        val groupCode = GroupCodeUtils.generateGroupCode()
        val nodeId = "node-aabbccdd"
        val deviceName = "TestDevice"

        // Create discovery payload in same format as MeshNetworkManager
        val payload = "$nodeId|$deviceName|$groupCode"
        val message = createDiscoveryMessage(nodeId, payload)

        // Serialize and deserialize
        val serialized = protocol.serialize(message)
        val deserialized = protocol.deserialize(serialized, serialized.size)

        assertNotNull(deserialized)

        // Parse payload back
        val parts = String(deserialized!!.payload).split("|")
        assertEquals(3, parts.size)
        assertEquals(nodeId, parts[0])
        assertEquals(deviceName, parts[1])
        assertEquals(groupCode, parts[2])
    }

    @Test
    fun `normalized and raw group codes match`() {
        // This test verifies that codes from different sources can be compared
        val rawCode = GroupCodeUtils.generateGroupCode()
        val formattedCode = GroupCodeUtils.formatGroupCode(rawCode)
        val normalizedFromFormatted = GroupCodeUtils.normalizeGroupCode(formattedCode)

        assertEquals(
            "Normalized formatted code should equal raw code",
            rawCode,
            normalizedFromFormatted,
        )
    }

    @Test
    fun `group code comparison is case-insensitive`() {
        val code = "ABCDEF"
        val codeLower = "abcdef"

        // Both should normalize to the same value
        assertEquals(
            GroupCodeUtils.normalizeGroupCode(code),
            GroupCodeUtils.normalizeGroupCode(codeLower),
        )

        // Both should be valid
        assertTrue(GroupCodeUtils.isValidGroupCode(code))
        assertTrue(GroupCodeUtils.isValidGroupCode(codeLower))
    }

    // === Discovery Payload Format Tests ===
    // These tests verify the discovery payload format is consistent

    @Test
    fun `discovery payload format is nodeId|deviceName|groupCode`() {
        val testCases = listOf(
            Triple("node-11111111", "Device1", "ABC123"),
            Triple("node-22222222", "BikeIntercom-Test", "OPEN"),
            Triple("node-aabbccdd", "My-Device", "XYZ789"),
        )

        for ((nodeId, deviceName, groupCode) in testCases) {
            val payload = "$nodeId|$deviceName|$groupCode"
            val message = createDiscoveryMessage(nodeId, payload)

            val serialized = protocol.serialize(message)
            val deserialized = protocol.deserialize(serialized, serialized.size)

            assertNotNull("Should deserialize: $payload", deserialized)

            val parts = String(deserialized!!.payload).split("|")
            assertEquals("Should have 3 parts", 3, parts.size)
            assertEquals("NodeId should match", nodeId, parts[0])
            assertEquals("DeviceName should match", deviceName, parts[1])
            assertEquals("GroupCode should match", groupCode, parts[2])
        }
    }

    @Test
    fun `OPEN is valid group code for no-group mode`() {
        val payload = "node-11111111|TestDevice|OPEN"
        val message = createDiscoveryMessage("node-11111111", payload)

        val serialized = protocol.serialize(message)
        val deserialized = protocol.deserialize(serialized, serialized.size)

        assertNotNull(deserialized)
        val parts = String(deserialized!!.payload).split("|")
        assertEquals("OPEN", parts[2])
    }

    // === Cross-Device Compatibility Tests ===
    // These simulate messages from different devices

    @Test
    fun `device A can parse discovery from device B`() {
        // Simulate device B sending a discovery message
        val deviceBNodeId = "node-ee0aad1b"
        val deviceBName = "BikeIntercom-DeviceB"
        val groupCode = "6J8TX8"
        val payload = "$deviceBNodeId|$deviceBName|$groupCode"

        val message = createDiscoveryMessage(deviceBNodeId, payload)
        val serialized = protocol.serialize(message)

        // Simulate device A receiving and parsing
        val deserialized = protocol.deserialize(serialized, serialized.size)

        assertNotNull("Device A should parse Device B's message", deserialized)

        val parts = String(deserialized!!.payload).split("|")
        assertEquals(deviceBNodeId, parts[0])
        assertEquals(deviceBName, parts[1])
        assertEquals(groupCode, parts[2])
    }

    @Test
    fun `matching group codes are detected correctly`() {
        val code1 = "ABC123"
        val code2 = "abc123" // Same code, different case

        val normalized1 = code1.uppercase()
        val normalized2 = code2.uppercase()

        assertEquals(
            "Uppercase codes should match",
            normalized1,
            normalized2,
        )
    }

    @Test
    fun `mismatched group codes are detected correctly`() {
        val code1 = "ABC123"
        val code2 = "XYZ789"

        val normalized1 = code1.uppercase()
        val normalized2 = code2.uppercase()

        assertNotEquals(
            "Different codes should not match",
            normalized1,
            normalized2,
        )
    }

    // === Edge Cases ===

    @Test
    fun `device name with special characters survives round-trip`() {
        val deviceName = "Bike_Intercom-Test123"
        val nodeId = "node-aabbccdd"
        val payload = "$nodeId|$deviceName|OPEN"

        val message = createDiscoveryMessage(nodeId, payload)
        val serialized = protocol.serialize(message)
        val deserialized = protocol.deserialize(serialized, serialized.size)

        assertNotNull(deserialized)
        val parts = String(deserialized!!.payload).split("|")
        assertEquals(deviceName, parts[1])
    }

    @Test
    fun `multiple discovery messages maintain unique IDs`() {
        val messages = (1..10).map { i ->
            val nodeId = "node-${String.format(java.util.Locale.US, "%08x", i)}"
            val payload = "$nodeId|Device$i|OPEN"
            createDiscoveryMessage(nodeId, payload)
        }

        val messageIds = messages.map { it.messageId }.toSet()
        assertEquals(
            "All message IDs should be unique",
            10,
            messageIds.size,
        )
    }

    // === Helper Functions ===

    private fun createDiscoveryMessage(sourceId: String, payload: String): MeshMessage {
        return MeshMessage(
            sourceId = sourceId,
            destinationId = "broadcast",
            messageType = MeshMessage.MessageType.DISCOVERY,
            payload = payload.toByteArray(),
        )
    }
}
