#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Enable peer-to-peer voice connectivity

set -e

echo "========================================"
echo "Enter-Comm P2P Voice Connectivity Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd "$(dirname "$0")/../../.." || exit 1
PROJECT_ROOT=$(pwd)

echo "Project root: $PROJECT_ROOT"
echo ""

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo "Checking environment..."

# Check for Java/Android SDK
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -1)
    echo -e "${GREEN}✓ Java found:${NC} $JAVA_VERSION"
else
    echo -e "${RED}✗ Java not found - please install JDK 17+${NC}"
    exit 1
fi

# Check for Gradle wrapper
if [ -f "./gradlew" ]; then
    echo -e "${GREEN}✓ Gradle wrapper found${NC}"
else
    echo -e "${RED}✗ Gradle wrapper not found${NC}"
    exit 1
fi

# Check for Android SDK
if [ -n "$ANDROID_HOME" ] || [ -n "$ANDROID_SDK_ROOT" ]; then
    echo -e "${GREEN}✓ Android SDK configured${NC}"
else
    echo -e "${YELLOW}! ANDROID_HOME/ANDROID_SDK_ROOT not set - checking local.properties${NC}"
    if [ -f "local.properties" ]; then
        echo -e "${GREEN}✓ local.properties found${NC}"
    else
        echo -e "${RED}✗ Android SDK not configured${NC}"
        exit 1
    fi
fi

echo ""

# ============================================
# BUILD VERIFICATION
# ============================================

echo "Verifying build environment..."

# Run a quick Gradle check
if ./gradlew --version > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Gradle is working${NC}"
else
    echo -e "${RED}✗ Gradle failed to run${NC}"
    exit 1
fi

echo ""

# ============================================
# AVAILABLE COMMANDS
# ============================================

echo "========================================"
echo "Development Commands"
echo "========================================"
echo ""
echo "Build:"
echo "  make build          # Build debug APK"
echo "  make install        # Install on connected device"
echo "  make run            # Install and launch app"
echo ""
echo "Testing:"
echo "  make test           # Run unit tests"
echo "  make check          # Run all checks (format, detekt, lint, test)"
echo ""
echo "Logs:"
echo "  make logs           # Show filtered app logs"
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To start implementing, run the coder agent:"
echo ""
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 001 --parallel 1"
echo ""
